config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: %i[index new create show] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id }
  validates_length_of :comment, minimum: 6, too_short: 'please enter at least 6 characters'
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :image

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true

  def remote_poster_url
    "https://image.tmdb.org/t/p/w500#{poster_url}"
  end
end

app/models/title.rb
class Title < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @movies = Movie.all
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmark_params)

    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'list was successfully created.'
    else
      render :new, status: :unprocessable_entity # 422
    end
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name, :image, movie_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_bookmark.html.erb
<div id="<%= dom_id list %>">
  <p>
    <strong>Comment:</strong>
    <%= bookmark.comment %>
  </p>
</div>

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.collection_select :movie_id, @movies, :id, :title, include_blank: true %>
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<br>

<div>
  <%= link_to "Back to list",list_path(@list) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :image as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <p>
    <strong>Name:</strong>
    <%= list.name %>
  </p>
</div>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lists</h1>

<div id="lists" class="cards">
  <% @lists.each do |list| %>
   <div class="card-category"> <%= render list %>
    <p>
      <%= link_to "Show this list", list %>
      <%= image_tag list.image if list.image.attached? %>
    </p></div>
  <% end %>
</div>


<%= link_to "New list", new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= render @list %></h1>
<%= image_tag @list.image if @list.image.attached? %>

<% if @list.movies.any? %>
  <h2>Selected Movies:</h2>
  <ul>
    <% @list.movies.each do |movie| %>
      <li>
       <p><%= movie.title %></p>
        <p><%= image_tag  movie.remote_poster_url, width: 200 %></p>
        <% bookmark = Bookmark.find_by(list_id: @list.id, movie_id: movie.id) %>
        <% if bookmark.present? %>
          <p><%= bookmark.comment %></p>
          <%= link_to "Remove bookmark", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        <% else %>
          <p>No comment for this movie.</p>
        <% end %>
      </div></li>
    <% end %>
  </ul></div>
<% else %>
  <p>No movies selected.</p>
<% end %>

<%= link_to "Back to lists", lists_path %>
<%= link_to "Add a bookmark", new_list_bookmark_path(@list) %>